CREATE DATABASE IF NOT EXISTS `db_booking_homestay`;
USE `db_booking_homestay`;

CREATE TABLE `TABLE_TEMPLATE` (
	`id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,

  
	`deletedBy` INT NOT NULL DEFAULT 0,
	`isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
	`deletedAt` TIMESTAMP NULL DEFAULT NULL,
	`createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `roles` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL UNIQUE,
    `description` TEXT NULL,
    `isActive` TINYINT(1) NOT NULL DEFAULT 1,

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `users` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NULL,
    `firstName` VARCHAR(255) NOT NULL,
    `lastName` VARCHAR(255) NOT NULL,
    `phoneNumber` VARCHAR(20) NULL,
    `dateOfBirth` DATE NULL,
    `gender` ENUM('MALE','FEMALE','OTHER') NULL,
    `avatar` TEXT NULL,
    `country` VARCHAR(100) NULL,
    `isVerified` TINYINT(1) NOT NULL DEFAULT 0,
    `isActive` TINYINT(1) NOT NULL DEFAULT 0,

    `googleId` VARCHAR(255) NULL,
    `provider` ENUM('LOCAL','GOOGLE') NOT NULL DEFAULT 'LOCAL',
    `lastLogin` TIMESTAMP NULL DEFAULT NULL,

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `user_roles` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `userId` INT NOT NULL,
    `roleId` INT NOT NULL,
    FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`roleId`) REFERENCES `roles`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `user_role_unique` (`userId`,`roleId`)
);

CREATE TABLE `otp_codes` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `userId` INT NULL,
    `email` VARCHAR(255) NOT NULL,
    `otp` VARCHAR(10) NOT NULL,
    `expiresAt` TIMESTAMP NOT NULL,
    `isUsed` TINYINT(1) NOT NULL DEFAULT 0,
    FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL,

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `loyalty_levels` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL UNIQUE,
    `minPoints` INT NOT NULL DEFAULT 0,
    `description` VARCHAR(255) NULL,
    `isActive` TINYINT(1) NOT NULL DEFAULT 1

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `loyalty_program` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `userId` INT NOT NULL UNIQUE,
    FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE,

    `totalBookings` INT NOT NULL DEFAULT 0,
    `totalNights` INT NOT NULL DEFAULT 0,
    `points` INT NOT NULL DEFAULT 0,
    `levelId` INT NOT NULL,
    `lastUpgradeDate` TIMESTAMP NULL DEFAULT NULL,

    FOREIGN KEY (`levelId`) REFERENCES `loyalty_levels`(`id`),

    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `locations` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `province` VARCHAR(100) NOT NULL,
    `district` VARCHAR(100) NOT NULL,
    `ward` VARCHAR(100) NULL,
    `street` VARCHAR(255) NULL,
    `latitude` DECIMAL(10,7) NULL,
    `longitude` DECIMAL(10,7) NULL,
    
    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `rooms` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `hostId` INT NOT NULL,
    `locationId` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `price` DECIMAL(12,2) NOT NULL,

    `adultCapacity` INT NOT NULL,
    `childCapacity` INT NOT NULL DEFAULT 0,

    `status` ENUM('AVAILABLE','BOOKED','MAINTENANCE') DEFAULT 'AVAILABLE',

    `rating` DECIMAL(2,1) DEFAULT 0,
    `reviewCount` INT DEFAULT 0,

    FOREIGN KEY (`hostId`) REFERENCES `users`(`id`),
    FOREIGN KEY (`locationId`) REFERENCES `locations`(`id`),

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `room_beds` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `roomId` INT NOT NULL,
    `type` ENUM('SINGLE','DOUBLE','QUEEN','KING','SOFA_BED','BUNK_BED') NOT NULL,
    `quantity` INT NOT NULL DEFAULT 1,
    FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`) ON DELETE CASCADE,

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `room_prices` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `roomId` INT NOT NULL,
    `date` DATE NOT NULL,
    `price` DECIMAL(12,2) NOT NULL,
    FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`),

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `room_availability` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `roomId` INT NOT NULL,
    `date` DATE NOT NULL,
    `isAvailable` TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`),

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `amenities` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(100) NOT NULL UNIQUE,
    `description` VARCHAR(255) NULL,
    `category` ENUM('BASIC','BATHROOM','BEDROOM','COMMON') NOT NULL DEFAULT 'BASIC',

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `room_amenities` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `roomId` INT NOT NULL,
    `amenityId` INT NOT NULL,
    FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`amenityId`) REFERENCES `amenities`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `room_amenity_unique` (`roomId`,`amenityId`),
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `room_images` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `roomId` INT NOT NULL,
    `imageUrl` VARCHAR(255) NOT NULL,
    `isMain` TINYINT(1) NOT NULL DEFAULT 0,
    `position` INT NULL,
    FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`) ON DELETE CASCADE,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `bookings` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `userId` INT NOT NULL,
    `roomId` INT NOT NULL,
    `checkIn` DATE NOT NULL,
    `checkOut` DATE NOT NULL,
    `adults` INT NOT NULL,
    `children` INT NOT NULL DEFAULT 0,
    `totalPrice` DECIMAL(12,2) NOT NULL,
    `status` ENUM('PENDING','CONFIRMED','CHECKED_IN','CHECKED_OUT','CANCELLED','REFUNDED') DEFAULT 'PENDING',
    FOREIGN KEY (`userId`) REFERENCES `users`(`id`),
    FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`),
    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `payment_methods` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL UNIQUE,
    `description` VARCHAR(255) NULL,
    `isActive` TINYINT(1) NOT NULL DEFAULT 0,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `payments` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `bookingId` INT NOT NULL,
    `amount` DECIMAL(12,2) NOT NULL,
    `paymentMethodId` INT NOT NULL,
    `paymentGateway` VARCHAR(50) NULL,
    `transactionId` VARCHAR(255) NULL,
    `status` ENUM('PENDING','SUCCESS','FAILED') DEFAULT 'PENDING',
    `transactionDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`bookingId`) REFERENCES `bookings`(`id`),
    FOREIGN KEY (`paymentMethodId`) REFERENCES `payment_methods`(`id`),
    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `reviews` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `bookingId` INT NOT NULL,
    `userId` INT NOT NULL,
    `rating` DECIMAL(2,1) CHECK (rating >= 1.0 AND rating <= 5.0),
    `comment` VARCHAR(1000),
    FOREIGN KEY (`bookingId`) REFERENCES `bookings`(`id`),
    FOREIGN KEY (`userId`) REFERENCES `users`(`id`),

    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `contacts` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `userId` INT NULL,
    `fullName` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `message` VARCHAR(1000) NOT NULL,
    FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    `deletedBy` INT NOT NULL DEFAULT 0,
    `isDeleted` TINYINT(1) NOT NULL DEFAULT 0,
    `deletedAt` TIMESTAMP NULL DEFAULT NULL,
    `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
