export interface Country {
  code: string;
  name: string;
}

export const COUNTRIES: Country[] = [
  { code: "afghanistan", name: "Afghanistan" },
  { code: "albania", name: "Albania" },
  { code: "algeria", name: "Algeria" },
  { code: "andorra", name: "Andorra" },
  { code: "angola", name: "Angola" },
  { code: "argentina", name: "Argentina" },
  { code: "armenia", name: "Armenia" },
  { code: "australia", name: "Australia" },
  { code: "austria", name: "Austria" },
  { code: "azerbaijan", name: "Azerbaijan" },
  { code: "bahrain", name: "Bahrain" },
  { code: "bangladesh", name: "Bangladesh" },
  { code: "belgium", name: "Belgium" },
  { code: "brazil", name: "Brazil" },
  { code: "canada", name: "Canada" },
  { code: "china", name: "China" },
  { code: "czech", name: "Czech Republic" },
  { code: "denmark", name: "Denmark" },
  { code: "egypt", name: "Egypt" },
  { code: "finland", name: "Finland" },
  { code: "france", name: "France" },
  { code: "germany", name: "Germany" },
  { code: "greece", name: "Greece" },
  { code: "hungary", name: "Hungary" },
  { code: "india", name: "India" },
  { code: "indonesia", name: "Indonesia" },
  { code: "ireland", name: "Ireland" },
  { code: "italy", name: "Italy" },
  { code: "japan", name: "Japan" },
  { code: "kazakhstan", name: "Kazakhstan" },
  { code: "kenya", name: "Kenya" },
  { code: "malaysia", name: "Malaysia" },
  { code: "mexico", name: "Mexico" },
  { code: "netherlands", name: "Netherlands" },
  { code: "newzealand", name: "New Zealand" },
  { code: "norway", name: "Norway" },
  { code: "pakistan", name: "Pakistan" },
  { code: "philippines", name: "Philippines" },
  { code: "poland", name: "Poland" },
  { code: "portugal", name: "Portugal" },
  { code: "russia", name: "Russia" },
  { code: "singapore", name: "Singapore" },
  { code: "southafrica", name: "South Africa" },
  { code: "southkorea", name: "South Korea" },
  { code: "spain", name: "Spain" },
  { code: "sweden", name: "Sweden" },
  { code: "switzerland", name: "Switzerland" },
  { code: "thailand", name: "Thailand" },
  { code: "turkey", name: "Turkey" },
  { code: "uk", name: "United Kingdom" },
  { code: "usa", name: "United States" },
  { code: "vietnam", name: "Vietnam" },
  // ... bạn có thể tiếp tục thêm tất cả các quốc gia
];
