export enum NotificationType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_REFUNDED = 'BOOKING_REFUNDED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  CHECKIN_REMINDER = 'CHECKIN_REMINDER',
  NEW_MESSAGE = 'NEW_MESSAGE',
  ADMIN_BOOKING_CREATED = 'ADMIN_BOOKING_CREATED',
  ADMIN_PAYMENT_SUCCESS = 'ADMIN_PAYMENT_SUCCESS',
  ADMIN_BOOKING_CANCELLED = 'ADMIN_BOOKING_CANCELLED',
  ADMIN_CHECKIN_REMINDER = 'ADMIN_CHECKIN_REMINDER',
  ADMIN_BOOKING_WAITING_REFUND = 'ADMIN_BOOKING_WAITING_REFUND',
  ADMIN_EXPECTED_CHECKIN_REQUEST = 'ADMIN_EXPECTED_CHECKIN_REQUEST',
  EXPECTED_CHECKIN_RESULT = 'EXPECTED_CHECKIN_RESULT',
  ADMIN_UNCONFIRMED_CHECKIN = 'ADMIN_UNCONFIRMED_CHECKIN',
  ADMIN_UNCONFIRMED_CHECKOUT = 'ADMIN_UNCONFIRMED_CHECKOUT',
  ADMIN_SUSPECTED_NOSHOW = 'ADMIN_SUSPECTED_NOSHOW',
}

export type NotificationTargetType = 'booking' | 'conversation';

export type NotificationData = {
  actionUrl?: string;
  targetType?: NotificationTargetType;
  targetId?: number;
  bookingId?: number;
  conversationId?: number;
  fromUserId?: number;
  status?: string;
  paidAmount?: number;
  refundAmount?: number;
  guestName?: string;
  checkIn?: Date | string;
};
